.TH "/home/kajanan/Github/ray_tracer/src/common/include/common/common_types.hpp" 3 "Fri Dec 24 2021" "ray_tracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kajanan/Github/ray_tracer/src/common/include/common/common_types.hpp \- Contains definitions for common types\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBRayTracer::u8\fP = uint8_t"
.br
.RI "8 bit unsigned integer "
.ti -1c
.RI "using \fBRayTracer::u16\fP = uint16_t"
.br
.RI "16 bit unsigned integer "
.ti -1c
.RI "using \fBRayTracer::u32\fP = uint32_t"
.br
.RI "32 bit unsigned integer "
.ti -1c
.RI "using \fBRayTracer::u64\fP = uint64_t"
.br
.RI "64 bit unsigned integer "
.ti -1c
.RI "using \fBRayTracer::s8\fP = int8_t"
.br
.RI "8 bit signed integer "
.ti -1c
.RI "using \fBRayTracer::s16\fP = int16_t"
.br
.RI "16 bit signed integer "
.ti -1c
.RI "using \fBRayTracer::s32\fP = int32_t"
.br
.RI "32 bit signed integer "
.ti -1c
.RI "using \fBRayTracer::s64\fP = int64_t"
.br
.RI "64 bit signed integer "
.ti -1c
.RI "using \fBRayTracer::f32\fP = float"
.br
.RI "32 bit floating point "
.ti -1c
.RI "using \fBRayTracer::f64\fP = double"
.br
.RI "64 bit floating point "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBRayTracer::ImageEncodings\fP { \fBkRGB8\fP, \fBkBGR8\fP }"
.br
.RI "Supported image encodings\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains definitions for common types\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBRayTracer::ImageEncodings\fP\fC [strong]\fP"

.PP
Supported image encodings\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkRGB8 \fP\fP
RGB8 image\&. 
.TP
\fB\fIkBGR8 \fP\fP
BGR8 image\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ray_tracer from the source code\&.
