.TH "/home/kajanan/Github/ray_tracer/src/image_utils/include/image_utils/image.hpp" 3 "Fri Dec 24 2021" "ray_tracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kajanan/Github/ray_tracer/src/image_utils/include/image_utils/image.hpp \- Contains the definition of an image struct\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'common/common_types\&.hpp'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'cuda\&.h'\fP
.br
\fC#include 'cuda_runtime\&.h'\fP
.br
\fC#include 'common/cuda_memory_utils\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRayTracer::Image\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the definition of an image struct\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for ray_tracer from the source code\&.
