.TH "RayTracer::Hello" 3 "Wed Dec 22 2021" "ray_tracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::Hello \- \fBHello\fP llo\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common_types\&.hpp>\fP
.SH "Detailed Description"
.PP 
\fBHello\fP llo\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ray_tracer from the source code\&.
