.TH "RayTracer::vector3< T >" 3 "Fri Dec 24 2021" "ray_tracer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RayTracer::vector3< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvector3\fP (T x, T y, T z)"
.br
.ti -1c
.RI "__device__ __host__ T & \fBx\fP ()"
.br
.ti -1c
.RI "__device__ __host__ T & \fBy\fP ()"
.br
.ti -1c
.RI "__device__ __host__ T & \fBz\fP ()"
.br
.ti -1c
.RI "__device__ __host__ const T & \fBx\fP () const"
.br
.ti -1c
.RI "__device__ __host__ const T & \fBy\fP () const"
.br
.ti -1c
.RI "__device__ __host__ const T & \fBz\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ray_tracer from the source code\&.
